const { createActions } = require('redux-actions')

module.exports = createActions(
  'SET_CHANNELS',
  'SET_CHANNEL',
  'UNSET_CHANNELS',
  'UNSET_CHANNEL',
  'UNDIRTY_CHANNELS',
  'UNDIRTY_CHANNEL',
  'CREATE_CHANNEL',
  'UPDATE_CHANNEL',
  'MOVE_TRANSITION_CHANNEL',
  'MOVE_PRIMARY_TRACK_CHANNEL',
  'RESIZE_CHANNEL',
  'SET_CHANNEL_PARENT',
  'CREATE_PRIMARY_TRACK_FROM_FILE',
  'SWAP_PRIMARY_TRACKS'
)
