const { createActions } = require('redux-actions')

module.exports = createActions(
  'SET_CHANNELS',
  'SET_CHANNEL',
  'UNSET_CHANNELS',
  'UNSET_CHANNEL',
  'UNDIRTY_CHANNELS',
  'UNDIRTY_CHANNEL',
  'CREATE_CHANNEL',
  'UPDATE_CHANNEL',
  'RESIZE_CHANNEL',
  'SET_CLIPS_CHANNEL',
  'SET_CHANNELS_PARENT',
  'SWAP_CHANNELS',
  'MOVE_TRACK_GROUP',
  'CREATE_TRACK_GROUP_FROM_FILE'
)
